# Example Site settings

#google_analytics: UA-NNNNNNNN-N

title: 'rumaiiis.github.io'
description: "PlayGround"
baseurl: "/"
url: "https://rumaiiis.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: hacker 


plugins:
  - jekyll-seo-tag
