
#google_analytics: UA-NNNNNNNN-N

title: 'rumaiiis.github.io'
description: "PlayGround"
baseurl: "/"
url: "https://rumaiiis.github.io"

header_pages:
  - index.md
  - blog.md
  - poc.md
  - about.md
  - contact.md

#footer: ''



style: hacker 


plugins:
  - jekyll-seo-tag
